# -*- coding: UTF-8 -*-

# Generated by Django 2.2.6 on 2019-11-04 17:15

# datamigrations: fill data on homepage

from django.db import migrations

def fill_pages(apps, schema_editor):
    HtmlContent = apps.get_model('pages', 'HtmlContent')
    data = [
        {'keyword': 'homepage-content', 'content': '<p>Cośtam jest innego</p>'},
    ]
    for el in data:
        if 'keyword' not in el:
            continue
        if 'content' not in el:
            continue
        hc = HtmlContent.objects.filter(keyword=el['keyword'])
        if hc.count() != 0:
            hc = hc[0]
        else:
            hc = HtmlContent()
            hc.keyword = el['keyword']
        hc.content = el['content']
        hc.save()
    return

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_pages),
    ]
